main_module = "oml.py"
main_module_prefix = "oml"
version = "0.1.0"


# TODO: is this necessary?
[irkpackage]
uri = "irk:/oml_work/1.0"
title = "OML"
description = "A machine learning knowledge graph with items and relations."
